version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: streamer
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./config/:/config
      - "/mnt/data/media/transcodes/cache:/config/Library/Application Support/Plex Media Server/Cache/"
      - /mnt/data/media/transcodes:/transcodes
      - /mnt/data/media/:/media
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: proxy
